source 'https://rubygems.org/'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'

group :development do
  gem 'sinatra-contrib'
  gem 'stackprof'
  gem 'newrelic_rpm'
end

group :test do
  gem 'rspec'
end
